name: LyoApp
options:
  bundleIdPrefix: com.lyo.production
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

targets:
  LyoApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: LyoApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lyo.production.app
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        SWIFT_VERSION: "5.0"
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SUPPORTS_MACCATALYST: NO
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
      debug:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      release:
        SWIFT_COMPILATION_MODE: wholemodule
    info:
      path: LyoApp/Info.plist
      properties:
        CFBundleDisplayName: Lyo
        CFBundleName: LyoApp
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        NSCameraUsageDescription: "Lyo uses camera for profile pictures and educational content"
        NSPhotoLibraryUsageDescription: "Lyo accesses photos for content sharing and learning materials"
        NSMicrophoneUsageDescription: "Lyo uses microphone for voice messages and educational recordings"
        NSLocationWhenInUseUsageDescription: "Lyo uses location for personalized learning recommendations"
