name: LyoApp
options:
  bundleIdPrefix: com.lyo
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

targets:
  LyoApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    dependencies:
      - package: Nuke
    sources:
      - path: LyoApp
        excludes:
          - "**/*_Clean*"
          - "**/*_Simple*"
          - "**/*_Fixed*"
          - "**/*_Enhanced*"
          - "**/*_Old*" 
          - "**/*_backup*"
          - "**/*_clean*"
          - "**/*_simple*"
          - "**/*_fixed*"
          - "**/*_enhanced*"
          - "**/*_old*"
          - "**/*.backup"
          - "**/*.disabled"
          - "**/*.bak"
          - "**/*.xcdatamodeld"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lyo.app
        DEVELOPMENT_TEAM: "5QZDMJGN7B"
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        SWIFT_VERSION: "5.0"
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SUPPORTS_MACCATALYST: NO
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGNING_REQUIRED: YES
      debug:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      release:
        SWIFT_COMPILATION_MODE: wholemodule
    info:
      path: LyoApp/Info.plist
      properties:
        CFBundleDisplayName: Lyo
        CFBundleName: LyoApp
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        NSCameraUsageDescription: "Lyo uses camera for profile pictures and content creation"
        NSPhotoLibraryUsageDescription: "Lyo accesses photos for profile pictures and content sharing"
        NSMicrophoneUsageDescription: "Lyo uses microphone for video content and voice messages"
