name: LyoApp_AI
options:
  bundleIdPrefix: com.lyoapp.ai
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  developmentLanguage: en
  indentWidth: 4
  tabWidth: 4

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"

targets:
  LyoApp_AI:
    type: application
    platform: iOS
    sources:
      - path: App
        group: App
      - path: Services
        group: Services
      - path: Models
        group: Models
      - path: DesignSystem
        group: DesignSystem
      - path: Features
        group: Features
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lyoapp.ai
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: true
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1"
    info:
      path: Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleDisplayName: "Lyo AI"
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        LSRequiresIPhoneOS: true
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        LSApplicationQueriesSchemes:
          - https
          - http
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
          NSExceptionDomains:
            localhost:
              NSExceptionAllowsInsecureHTTPLoads: true
              NSExceptionMinimumTLSVersion: "1.0"
        NSCameraUsageDescription: "This app needs access to camera to upload photos"
        NSPhotoLibraryUsageDescription: "This app needs access to photo library to upload images"

schemes:
  LyoApp_AI:
    build:
      targets:
        LyoApp_AI: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
